
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzoapasbstngozkdyuka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6b2FwYXNic3RuZ296a2R5dWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MTc1NjcsImV4cCI6MjA2MzE5MzU2N30.sV1xEFEZnbxPyWS6fpmSN0RI4QXgQyOY-tn-3XAxp3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
